# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dostavka1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dostavka1


  target 'dostavka1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

